name: ESLint
on: [push, pull_request]

jobs:
  update:
    name: ESLint

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node v12
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Enforce npm 8
        run: npm install -g npm@8.x
      - name: Run CI-Setup
        working-directory: ./bundle
        run: npm run cisetup
      - name: Run ESLint
        working-directory: ./bundle
        run: npm run eslint:fix
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: .
          message: "(lint): Auto-fix linting errors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}