name: Publish Tag and Release


on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

jobs:
  tag:
    name: Publish Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.current_version.outputs.version }}
      skip: ${{ steps.compare_versions.outputs.skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Current version
        id: current_version
        run: echo version=v$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

      - name: Compare latest tag
        id: git_version
        run: |
          git fetch --tags
          echo latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`) >> $GITHUB_OUTPUT

      - name: Compare versions and skip if same
        id: compare_versions
        if: ${{ steps.current_version.outputs.version == steps.git_version.outputs.latest_tag }}
        run: echo "skip=true" >> $GITHUB_OUTPUT && echo "Skipping publish because versions are the same" && exit 0

      - name: Push Tag
        if: ${{ steps.compare_versions.outputs.skip != 'true' }}
        id: tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "${{ steps.current_version.outputs.version }}"


  release:
    needs: tag
    name: Publish Release
    runs-on: ubuntu-latest

    if: ${{ needs.tag.outputs.skip != 'true' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci

      - name: Generate Dist Files
        run: npm run dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/arunacore.zip
          tag_name: ${{ needs.tag.outputs.version }}

  publish-docker:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update Docker Image
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BOT_SECRET }}
          event-type: publish-docker-image
          repository: ArunaBot/ArunaCore-Docker

