name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Test
        working-directory: ./bundle
        run: npm run test
      - name: Commit changes (if exists)
        uses: EndBug/add-and-commit@v4
        with:
          add: .
          message: "(lint): Auto-fix linting errors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}