name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Update NPM
        run: npm install -g npm@8.x

      - name: Run Test
        run: npm run test
